language: node_js
node_js: '9'

before_install:
  - stty cols 80

dist: trusty
sudo: required

addons:
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.18.0
    - COMMIT=${TRAVIS_COMMIT::8}
    - MAIN_REPO=https://github.com/testdrivenio/testdriven-app-2.2.git
    - USERS=test-driven-users
    - USERS_REPO=${MAIN_REPO}#${TRAVIS_BRANCH}:services/users
    - USERS_DB=test-driven-users_db
    - USERS_DB_REPO=${MAIN_REPO}#${TRAVIS_BRANCH}:services/users/project/db
    - CLIENT=test-driven-client
    - CLIENT_REPO=${MAIN_REPO}#${TRAVIS_BRANCH}:services/client
    - SWAGGER=test-driven-swagger
    - SWAGGER_REPO=${MAIN_REPO}#${TRAVIS_BRANCH}:services/swagger
    - EXERCISES=test-driven-exercises
    - EXERCISES_REPO=${MAIN_REPO}#${TRAVIS_BRANCH}:services/exercises
    - EXERCISES_DB=test-driven-exercises_db
    - EXERCISES_DB_REPO=${MAIN_REPO}#${TRAVIS_BRANCH}:services/exercises/project/db

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - export TEST_URL=http://127.0.0.1
  - export REACT_APP_USERS_SERVICE_URL=http://127.0.0.1
  - export REACT_APP_EXERCISES_SERVICE_URL=http://127.0.0.1
  - export REACT_APP_API_GATEWAY_URL=https://69n19z0lo3.execute-api.us-west-1.amazonaws.com/v1/execute
  - export SECRET_KEY=my_precious
  - export DISPLAY=:99.0
  - export DOCKER_ENV=$(if [ "$TRAVIS_BRANCH" == "production" ]; then echo "prod"; else echo "stage"; fi)
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - docker-compose -f docker-compose-stage.yml up --build -d

script:
  - bash test.sh $DOCKER_ENV

after_script:
  - docker-compose -f docker-compose-stage.yml down

after_success:
  - bash ./docker-push.sh
  - bash ./docker-deploy-stage.sh
  - bash ./docker-deploy-prod.sh
