version: '3.4'

services:

  users:
    container_name: users
    build:
      context: ./services/users
      dockerfile: Dockerfile-prod
    expose:
      - 5000
    environment:
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - users-db
    links:
      - users-db

  users-db:
    container_name: users-db
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  client:
    container_name: client
    build:
      context: ./services/client
      dockerfile: Dockerfile-prod
      args:
        - NODE_ENV=production
        - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
        - REACT_APP_API_GATEWAY_URL=${REACT_APP_API_GATEWAY_URL}
        - REACT_APP_EXERCISES_SERVICE_URL=${REACT_APP_EXERCISES_SERVICE_URL}
    expose:
      - 80
    depends_on:
      - users
    links:
      - users

  nginx:
    container_name: nginx
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - users
      - client

  swagger:
    container_name: swagger
    build:
      context: ./services/swagger
      dockerfile: Dockerfile-prod
    expose:
      - 8080
    environment:
      - URL=swagger.json
    depends_on:
      - users

  exercises:
    container_name: exercises
    build:
      context: ./services/exercises
      dockerfile: Dockerfile-prod
    expose:
      - 5000
    environment:
      - APP_SETTINGS=project.config.StagingConfig
      - DATABASE_URL=postgres://postgres:postgres@exercises-db:5432/exercises_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@exercises-db:5432/exercises_test
    depends_on:
      - users
      - exercises-db
    links:
      - users
      - exercises-db

  exercises-db:
    container_name: exercises-db
    build:
      context: ./services/exercises/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
